apiVersion: v1
kind: Secret
metadata:
  name: apache-airflow
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://airflow.apache.org/
  name: airflow
  type: helm