apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  # You should replace this with the URL of your GitHub repository
  url: https://github.com/chimeyrock999/PhishingURLDetection.git
  name: chimeyrock999