apiVersion: v1
kind: Secret
metadata:
  name: prometheus-community
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://prometheus-community.github.io/helm-charts
  name: prometheus-community
  type: helm