apiVersion: v1
kind: Secret
metadata:
  name: spark-operator
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://kubeflow.github.io/spark-operator
  name: spark-operator
  type: helm