apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner-set
  namespace: argocd
spec:
  destination:
    namespace: arc-runners
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gha-runner-scale-set
    helm:
      valueFiles:
        - values.yaml
      values: |-
        githubConfigUrl: https://github.com/chimeyrock999/PhishingURLDetection
        githubConfigSecret:
          github_token: nothing_here
        controllerServiceAccount:
          namespace: arc-systems
          name: gha-runner-scale-set-controller-gha-rs-controller
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.9.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
