apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: prometheus-operator
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: installCRDs
          value: 'true'
    repoURL: https://openchart.choerodon.com.cn/choerodon/c7n
    targetRevision: 9.3.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:  
      - CreateNamespace=true
      - PrunePropagationPolicy=background
