name: Resources Sync

on:
  push:
    paths:
      - manifests/*

jobs:
  sync:
    runs-on: arc-runner-set
    steps:
      - name: Login ArgoCD
        run: echo "Login ArgoCD"
      - name: Application Sync
        run: echo "Sync github application"